/*
 * YtelAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPI.Standard;
using YtelAPI.Standard.Utilities;


namespace YtelAPI.Standard.Models
{
    public class AddressListaddressInput : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? page = 1;
        private int? pagesize = 10;
        private string addressid;
        private string dateCreated;

        /// <summary>
        /// The page count to retrieve from the total results in the collection. Page indexing starts at 1.
        /// </summary>
        [JsonProperty("page")]
        public int? Page 
        { 
            get 
            {
                return this.page; 
            } 
            set 
            {
                this.page = value;
                onPropertyChanged("Page");
            }
        }

        /// <summary>
        /// How many results to return, default is 10, max is 100, must be an integer
        /// </summary>
        [JsonProperty("pagesize")]
        public int? Pagesize 
        { 
            get 
            {
                return this.pagesize; 
            } 
            set 
            {
                this.pagesize = value;
                onPropertyChanged("Pagesize");
            }
        }

        /// <summary>
        /// addresses Sid
        /// </summary>
        [JsonProperty("addressid")]
        public string Addressid 
        { 
            get 
            {
                return this.addressid; 
            } 
            set 
            {
                this.addressid = value;
                onPropertyChanged("Addressid");
            }
        }

        /// <summary>
        /// date created address.
        /// </summary>
        [JsonProperty("dateCreated")]
        public string DateCreated 
        { 
            get 
            {
                return this.dateCreated; 
            } 
            set 
            {
                this.dateCreated = value;
                onPropertyChanged("DateCreated");
            }
        }
    }
} 