/*
 * YtelAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPI.Standard;
using YtelAPI.Standard.Utilities;


namespace YtelAPI.Standard.Models
{
    public class CreateUserDeletesubaccountInput : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string subAccountSID;
        private Models.MergeNumberEnum mergeNumber;

        /// <summary>
        /// The SubaccountSid to be deleted
        /// </summary>
        [JsonProperty("SubAccountSID")]
        public string SubAccountSID 
        { 
            get 
            {
                return this.subAccountSID; 
            } 
            set 
            {
                this.subAccountSID = value;
                onPropertyChanged("SubAccountSID");
            }
        }

        /// <summary>
        /// 0 to delete or 1 to merge numbers to parent account.
        /// </summary>
        [JsonProperty("MergeNumber")]
        public Models.MergeNumberEnum MergeNumber 
        { 
            get 
            {
                return this.mergeNumber; 
            } 
            set 
            {
                this.mergeNumber = value;
                onPropertyChanged("MergeNumber");
            }
        }
    }
} 