/*
 * YtelAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPI.Standard;
using YtelAPI.Standard.Utilities;


namespace YtelAPI.Standard.Models
{
    public class Error : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string code;
        private string message;
        private List<string> moreInfo;

        /// <summary>
        /// Error Response Code
        /// </summary>
        [JsonProperty("Code")]
        public string Code 
        { 
            get 
            {
                return this.code; 
            } 
            set 
            {
                this.code = value;
                onPropertyChanged("Code");
            }
        }

        /// <summary>
        /// Error Response Message
        /// </summary>
        [JsonProperty("Message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// Detailed Error Info
        /// </summary>
        [JsonProperty("MoreInfo")]
        public List<string> MoreInfo 
        { 
            get 
            {
                return this.moreInfo; 
            } 
            set 
            {
                this.moreInfo = value;
                onPropertyChanged("MoreInfo");
            }
        }
    }
} 