/*
 * YtelAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using YtelAPI.Standard;
using YtelAPI.Standard.Utilities;

namespace YtelAPI.Standard.Models
{
    public enum ProductCodeEnum
    {
        ALL = 0, //TODO: Write general description for this method
        ENUM_1 = 1, //TODO: Write general description for this method
        ENUM_2 = 2, //TODO: Write general description for this method
        ENUM_3 = 3, //TODO: Write general description for this method
        ENUM_4 = 4, //TODO: Write general description for this method
        TRANSCRIPTION = 5, //TODO: Write general description for this method
        EMAIL = 6, //TODO: Write general description for this method
        CONFERENCE = 7, //TODO: Write general description for this method
        CARRIER = 8, //TODO: Write general description for this method
        ENUM_9 = 9, //TODO: Write general description for this method
        ENUM_10 = 10, //TODO: Write general description for this method
        ENUM_11 = 11, //TODO: Write general description for this method
        ENUM_12 = 12, //TODO: Write general description for this method
        ENUM_13 = 13, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type ProductCodeEnum
    /// </summary>
    public static class ProductCodeEnumHelper
    {
        /// <summary>
        /// Convert a list of ProductCodeEnum values to a list of integers
        /// </summary>
        /// <param name="enumValues">The list of ProductCodeEnum values to convert</param>
        /// <returns>The list of representative integer values</returns>
        public static List<int> ToValue(List<ProductCodeEnum> enumValues)
        {
            if (null == enumValues)
                return null;
            
            return enumValues.Select(eVal => (int)eVal).ToList();
        }
    }
} 