/*
 * YtelAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPI.Standard;
using YtelAPI.Standard.Utilities;

namespace YtelAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum Status24Enum
    {
        CANCELED, //Interrupt Call will be cancel
        COMPLETED, //Interrupt Call is complete
    }

    /// <summary>
    /// Helper for the enum type Status24Enum
    /// </summary>
    public static class Status24EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "canceled", "completed" };

        /// <summary>
        /// Converts a Status24Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The Status24Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(Status24Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case Status24Enum.CANCELED:
                case Status24Enum.COMPLETED:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of Status24Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of Status24Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<Status24Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into Status24Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed Status24Enum value</returns>
        public static Status24Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type Status24Enum", value));

            return (Status24Enum) index;
        }
    }
} 